version: '3.7'

services:
  web-master:
    image: wylswz/nginx-swarm
    ports:
      - target: 8080
        published: 80
        protocol: tcp
        mode: ingress
      - target: 5984
        published: 5984
        protocol: tcp
        mode: host
    
    volumes:
      - './etc/nginx-master:/etc/nginx'
      - './src:/usr/share/nginx/html'
      - '/etc/hosts:/etc/hosts'

    command: [nginx, '-g', 'daemon off;']
    networks:
      nginx-net:
    deploy:
      placement:
        constraints:
          - node.role == manager
  web-slave:
    image: wylswz/nginx-swarm

    volumes:
      - './etc/nginx-slave:/etc/nginx'
      - './src:/usr/share/nginx/html'
      - '/etc/hosts:/etc/hosts'
    command: [nginx, '-g', 'daemon off;']
    networks:
      nginx-net:
    deploy:
      placement:
        constraints:
          - node.role == worker
      mode: replicated
      replicas: 3

networks:
  nginx-net:
    driver: overlay

    