- name: Collect facts
  hosts: localhost
  tasks:

    - os_server_facts:
        auth:
          auth_url: "{{lookup('env','OS_AUTH_URL')}}"
          username: "{{lookup('env','OS_USERNAME')}}"
          password: "{{lookup('env','OS_PASSWORD')}}"
          project_name: "{{lookup('env','OS_PROJECT_NAME')}}"
        server: 
      register: facts


- name: Deploy spark
  hosts:
    - master-instance
    - slave-instance-1
    - slave-instance-2
    - slave-instance-3
  become: yes
  become_method: sudo
  tasks:
    - file:
        path: /mnt/data
        state: directory
        mode: 0755
    - file:
        path: /etc/spark_conf
        state: directory
        mode: 0755
    - file:
        path: /home/ubuntu/spark
        state: directory
        mode: 0755
    - name: Sending compose file
      copy:
        src: "{{playbook_dir}}/compose-files/spark/docker-compose-swarm.yml"
        dest: "/home/ubuntu/spark/docker-compose.yml"
        mode: '666'
        directory_mode: yes
  

