#-------------------------------------Safe--------------------------------#
- name: Collect facts
  hosts: localhost
  tasks:

    - os_server_facts:
        auth:
          auth_url: "{{lookup('env','OS_AUTH_URL')}}"
          username: "{{lookup('env','OS_USERNAME')}}"
          password: "{{lookup('env','OS_PASSWORD')}}"
          project_name: "{{lookup('env','OS_PROJECT_NAME')}}"
        server: 
      register: facts

- name: Test
  hosts: localhost


- name: Send front-end source
  hosts:
    - master-instance
    - slave-instance-1
    - slave-instance-2
    - slave-instance-3
  become: yes
  become_method: sudo
  tasks:
    - file:
          path: "/home/ubuntu/frontend"
          state: absent
    - copy:
        src: "{{playbook_dir}}/../../frontend" 
        dest: "/home/ubuntu/"
        owner: "ubuntu"
        group: "ubuntu"
        mode: '666'
        directory_mode: yes
    - file:
        path: "/home/ubuntu/frontend"
        state: directory
        mode: 0777
        recurse: yes
